name: aasa_emr
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  pdf: ^3.10.8
  http: ^1.2.0
  intl: ^0.19.0
  rename: ^3.0.2
  provider: ^6.1.1
  printing: ^5.12.0
  timelines: ^0.1.0
  open_file: ^3.3.2
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.9
  filter_list: ^1.0.2
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  roundcheckbox: ^2.0.5
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  cool_dropdown: ^2.1.0
  # jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  otp_text_field_v2: ^1.0.3
  simple_animations: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  dotted_dashed_line: ^0.0.3
  flutter_native_splash: any
  permission_handler: ^11.3.0
  form_field_validator: ^1.1.0
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.1
  flutter_otp_text_field: ^1.1.1
  document_file_save_plus: ^2.0.0
  animated_custom_dropdown: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  searchable_paginated_dropdown: ^1.3.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  firebase_core: ^2.29.0
  firebase_analytics: ^10.10.1
  firebase_crashlytics: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  flutter_gen_runner:

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"

  android_12:
    image: "assets/images/splash_icon_a_12.png"

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/gif/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
