List<String> listOfDoctors = [
  'Dr. Ashok Gupta',
  'Dr. Priya Sharma',
  'Dr. Rajesh Patel',
  'Dr. Nisha Singh',
  'Dr. Vikram Malhotra',
  'Dr. Anjali Desai',
  'Dr. Sunil Kumar',
  'Dr. Preeti Mehta',
  'Dr. Rakesh Sharma',
  'Dr. Sunita Reddy',
  'Dr. Sanjay Choudhary Patel Patel Patel Patel Patel Patel Patel Patel Patel Patel',
  'Dr. Deepa Singhania',
  'Dr. Ajay Kumar',
  'Dr. Ananya Sen',
  'Dr. Vivek Verma',
  'Dr. Aarti Joshi',
  'Dr. Manish Gupta',
  'Dr. Meena Singh',
  'Dr. Rahul Kapoor',
  'Dr. Anuradha Rastogi',
];
