List<String> indianMedicalClinicNames = [
  'Healing Hands Clinic',
  'Care Plus Clinic',
  'Harmony Health Clinic',
  'Lotus Medical Center',
  'Hope Hospital & Clinic',
  'Wellness Clinic India',
  'Carewell Health Clinic',
  'Rainbow Clinic & Hospital',
  'Pristine Medical Centre',
  'Meditech Clinic',
  'Lifeline Healthcare Clinic',
  'Apex Medical Center',
  'Grace Clinic & Nursing Home',
  'Serenity Health Clinic',
  'Elite Care Clinic',
  'Sapphire Medical Centre',
  'Radiant Health Clinic',
  'Harmony Family Clinic',
  'Prime Health Centre',
  'Lotus Blossom Clinic',
];
