List<String> medicalConditions = [
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Arthritis",
  "Cancer",
  "Stroke",
  "Heart disease",
  "Obesity",
  "Depression",
  "Anxiety",
  "Schizophrenia",
  "Bipolar disorder",
  "Epilepsy",
  "Alzheimer's disease",
  "Parkinson's disease",
  "Chronic obstructive pulmonary disease (COPD)",
  "HIV/AIDS",
  "Migraine",
  "Fibromyalgia",
  "Multiple sclerosis (MS)",
  "Lupus",
  "Celiac disease",
  "Crohn's disease",
  "Ulcerative colitis",
  "Endometriosis",
  "Polycystic ovary syndrome (PCOS)",
  "Sleep apnea",
  "Chronic fatigue syndrome",
  "Rheumatoid arthritis",
  "Osteoporosis",
  "Gout",
  "Hemophilia",
  "Sickle cell disease",
  "Thalassemia",
  "Cystic fibrosis",
  "Tourette syndrome",
  "Autism spectrum disorder",
  "Attention deficit hyperactivity disorder (ADHD)",
  "Obsessive-compulsive disorder (OCD)",
  "Post-traumatic stress disorder (PTSD)",
  "Borderline personality disorder",
  "Binge eating disorder",
  "Bulimia nervosa",
  "Anorexia nervosa",
  "Substance use disorder",
  "Nicotine dependence",
  "Alcohol dependence",
  "Drug dependence",
  "Liver cirrhosis",
  "Chronic kidney disease",
  "Glaucoma",
  "Macular degeneration",
  "Cataracts",
  "Osteoarthritis",
  "Gastroesophageal reflux disease (GERD)",
  "Peptic ulcer disease",
  "Diverticulitis",
  "Gallstones",
  "Kidney stones",
  "Urinary tract infection (UTI)",
  "Chlamydia",
  "Gonorrhea",
  "Syphilis",
  "Genital herpes",
  "Genital warts",
  "Hepatitis B",
  "Hepatitis C",
  "Tuberculosis",
  "Malaria",
  "Dengue fever",
  "Chikungunya",
  "Zika virus",
  "Influenza",
  "Common cold",
  "Pneumonia",
  "Bronchitis",
  "Tonsillitis",
];
